### PR TITLE
I've translated the app into Spanish

### PR DESCRIPTION
**Pull request by ordago**

### CODE REVIEW

**Comment by cytodev** [comment]
You are an amazing person! Gracias!

@ordago If you could take the time to translate the play store description into Spanish that would be great! I will add it to the repo in a bit! You can find the playstore translations in the /PlayStore directory.

Also, you can add a little piece of your own to the play store description. You helped me out and I'm sure you did a great job!

**Comment by ordago** [comment]
Hi @CytoDev, sorry for the delay. Somehow I missed you message and found it while checking github.

I attatched the translation.

[FreqCalc Play description ES.txt](https://github.com/CytoDev/FrequencyCalculator/files/312495/FreqCalc.Play.description.ES.txt)

**Comment by cytodev** [comment]
@ordago I will update everything as soon as I fix the bugs you pointed out. Thanks again!

**Comment by cytodev** [comment]
@ordago Could you, by any chance, update the following files again? Some strings were added, and I liked the idea of crediting you.

In `/values-es/strings.xml` the [following lines](https://github.com/CytoDev/FrequencyCalculator/blob/master/app/src/main/res/values-es/strings.xml#L47-L50) have been added (GitHub does not allow highlighting of multiple files, so one of them is Spanish).

If you want your virtual internet karma credited to your real name, edit [this](https://github.com/CytoDev/FrequencyCalculator/blob/master/app/src/main/res/raw/translators.json#L5-L6).

To keep you from waiting for the update, here's the [direct link](https://github.com/CytoDev/FrequencyCalculator/releases/tag/V1.0.6-beta) to the file so you can check it out.

**Comment by ordago** [comment]
Done. 
I think I'll wait to put my real name on Github until I can make my own apps.

**Pull request merged**
